-- kintsugi-gram: 1:1 transcription of the "Kintsugi Dark Flared" Zed theme
-- shipped inside Gram.app (themes/kintsugi/kintsugi.json, by Giacomo Cavalieri).
--
-- Every color below comes from that JSON. Zed keys are mapped to their nvim
-- equivalent. Semi-transparent Zed values (#RRGGBBAA) are composited over the
-- editor background #161618, since nvim highlights have no alpha.
--
-- This is NOT the metalelf0/kintsugi-nvim port: Zed collapses the VSCode
-- entity.name.type / support.type split into a single `type` key, so types here
-- are orange (#E08542) like in Gram, not grey-green like in the faithful port.

local z = {
  -- style
  text            = "#BCAC8F",
  text_muted      = "#7F7B66",
  border          = "#2a2a28",
  border_focused  = "#b8943a",
  surface         = "#131314", -- panels, status bar, and every float here.
                               -- Zed puts popups on elevated_surface #292928,
                               -- which reads as a grey slab in nvim floats.
  bg              = "#161618",
  element_hover   = "#1c1c1d", -- element.hover #2a2a2850
  element_sel     = "#393b31",
  tab_inactive    = "#1a1a1d",
  fg              = "#dddddd", -- editor.foreground
  active_line     = "#1d1d1c",
  line_number     = "#444444",
  wrap_guide      = "#2a2a28",
  bracket_match   = "#31353c", -- document_highlight.bracket #6c7a8a50
  search_match    = "#2c2f35", -- search.match #6c7a8a40
  thumb           = "#262824", -- scrollbar.thumb #33352d90
  cursor          = "#E08542", -- players[0].cursor
  selection       = "#2f241d", -- players[0].selection #E0854220
  link_hover      = "#8fa3b3",
  conflict        = "#b38f8f",
  created         = "#a3be8c",
  deleted         = "#b38f8f",
  modified        = "#ebcb8b",
  error           = "#C97D7D",
  error_bg        = "#3b3132", -- error.background #8b6b6b50
  warning         = "#ebcb8b",
  warning_bg      = "#3b3b32", -- warning.background #8b8b6b50
  info            = "#6c7a8a",
  info_bg         = "#31363c", -- info.border #6b7b8b50
  hint            = "#dbac35",
  ignored         = "#75715e",
  hidden          = "#ccccc7",
  -- syntax
  attribute       = "#798283",
  boolean         = "#DB9833",
  comment         = "#5f5f5f",
  constant        = "#DB9833",
  constructor     = "#DBAD49",
  func            = "#798283",
  keyword         = "#D66848",
  label           = "#798283",
  number          = "#DB9833",
  operator        = "#E08542",
  preproc         = "#798283",
  property        = "#798283",
  punctuation     = "#7f7b66",
  string          = "#cc7f66",
  string_escape   = "#798283",
  tag             = "#DBAD49",
  text_literal    = "#cc7f66",
  title           = "#798283",
  type            = "#E08542",
  variable        = "#BCAC8F",
  -- terminal.ansi
  ansi = {
    "#131314", "#b38f8f", "#a3be8c", "#ebcb8b", "#6c7a8a", "#b3a3d3", "#6ac6f2", "#dddddd",
    "#444444", "#d9a6a6", "#c3de9c", "#fbe4a8", "#8fa3b3", "#d3a3d3", "#8ac6f2", "#ffffff",
  },
}

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "kintsugi-gram"

local hl = {
  -- editor
  Normal            = { fg = z.fg, bg = z.bg },
  NormalNC          = { fg = z.fg, bg = z.bg },
  NormalFloat       = { fg = z.text, bg = z.surface },
  FloatBorder       = { fg = z.border, bg = z.surface },
  FloatTitle        = { fg = z.text, bg = z.surface },
  Cursor            = { fg = z.surface, bg = z.cursor },
  lCursor           = { link = "Cursor" },
  TermCursor        = { link = "Cursor" },
  CursorLine        = { bg = z.active_line },
  CursorColumn      = { bg = z.active_line },
  ColorColumn       = { bg = z.active_line },
  LineNr            = { fg = z.line_number },
  CursorLineNr      = { fg = z.fg },
  SignColumn        = { bg = z.bg },
  FoldColumn        = { fg = z.line_number, bg = z.bg },
  Folded            = { fg = z.text_muted, bg = z.active_line },
  Visual            = { bg = z.selection },
  VisualNOS         = { bg = z.selection },
  Search            = { bg = z.search_match },
  IncSearch         = { fg = z.surface, bg = z.cursor },
  CurSearch         = { link = "IncSearch" },
  MatchParen        = { bg = z.bracket_match, bold = true },
  Whitespace        = { fg = z.wrap_guide },
  NonText           = { fg = z.wrap_guide },
  SpecialKey        = { fg = z.text_muted },
  EndOfBuffer       = { fg = z.bg },
  WinSeparator      = { fg = z.border, bg = z.bg },
  VertSplit         = { link = "WinSeparator" },
  Directory         = { fg = z.text },
  Title             = { fg = z.title, bold = true },
  Question          = { fg = z.info },
  MoreMsg           = { fg = z.created },
  ModeMsg           = { fg = z.text },
  WarningMsg        = { fg = z.warning },
  ErrorMsg          = { fg = z.error },
  Conceal           = { fg = z.text_muted },
  QuickFixLine      = { bg = z.element_sel },
  -- ui chrome
  StatusLine        = { fg = z.text, bg = z.surface },
  StatusLineNC      = { fg = z.text_muted, bg = z.surface },
  TabLine           = { fg = z.text_muted, bg = z.tab_inactive },
  TabLineSel        = { fg = z.fg, bg = z.bg },
  TabLineFill       = { bg = z.surface },
  WinBar            = { fg = z.text, bg = z.bg },
  WinBarNC          = { fg = z.text_muted, bg = z.bg },
  Pmenu             = { fg = z.text, bg = z.surface },
  PmenuSel          = { fg = z.fg, bg = z.element_sel },
  PmenuSbar         = { bg = z.surface },
  PmenuThumb        = { bg = z.thumb },
  PmenuKind         = { fg = z.type, bg = z.surface },
  PmenuExtra        = { fg = z.text_muted, bg = z.surface },
  MsgSeparator      = { fg = z.border },
  -- diff / git (derived: Zed has no editor diff backgrounds)
  DiffAdd           = { bg = "#2c302a" },
  DiffChange        = { bg = "#312d26" },
  DiffDelete        = { bg = "#2f292b" },
  DiffText          = { bg = "#4b4335" },
  Added             = { fg = z.created },
  Changed           = { fg = z.modified },
  Removed           = { fg = z.deleted },
  -- legacy syntax
  Comment           = { fg = z.comment, italic = true },
  Constant          = { fg = z.constant },
  String            = { fg = z.string },
  Character         = { fg = z.string },
  Number            = { fg = z.number },
  Boolean           = { fg = z.boolean },
  Float             = { fg = z.number },
  Identifier        = { fg = z.variable },
  Function          = { fg = z.func },
  Statement         = { fg = z.keyword, bold = true },
  Conditional       = { fg = z.keyword, bold = true },
  Repeat            = { fg = z.keyword, bold = true },
  Label             = { fg = z.label },
  Operator          = { fg = z.operator },
  Keyword           = { fg = z.keyword, bold = true },
  Exception         = { fg = z.keyword, bold = true },
  PreProc           = { fg = z.preproc },
  Include           = { fg = z.keyword, bold = true },
  Define            = { fg = z.preproc },
  Macro             = { fg = z.preproc },
  PreCondit         = { fg = z.preproc },
  Type              = { fg = z.type },
  StorageClass      = { fg = z.keyword, bold = true },
  Structure         = { fg = z.type },
  Typedef           = { fg = z.type },
  Special           = { fg = z.operator },
  SpecialChar       = { fg = z.string_escape },
  Tag               = { fg = z.tag, bold = true },
  Delimiter         = { fg = z.punctuation },
  SpecialComment    = { fg = z.comment, italic = true },
  Debug             = { fg = z.keyword },
  Underlined        = { fg = z.link_hover, underline = true },
  Bold              = { bold = true },
  Italic            = { italic = true },
  Error             = { fg = z.error },
  Todo              = { fg = z.hint, bold = true },
  -- treesitter
  ["@comment"]                = { link = "Comment" },
  ["@comment.documentation"]  = { fg = z.comment, italic = true },
  ["@comment.error"]          = { fg = z.error },
  ["@comment.warning"]        = { fg = z.warning },
  ["@comment.todo"]           = { link = "Todo" },
  ["@comment.note"]           = { fg = z.hint },
  ["@punctuation"]            = { fg = z.punctuation },
  ["@punctuation.bracket"]    = { fg = z.punctuation },
  ["@punctuation.delimiter"]  = { fg = z.punctuation },
  ["@punctuation.special"]    = { fg = z.punctuation },
  ["@string"]                 = { fg = z.string },
  ["@string.documentation"]   = { fg = z.string },
  ["@string.escape"]          = { fg = z.string_escape },
  ["@string.regexp"]          = { fg = z.string },
  ["@string.special"]         = { fg = z.string },
  ["@string.special.symbol"]  = { fg = z.string },
  ["@string.special.url"]     = { fg = z.link_hover, underline = true },
  ["@string.special.path"]    = { fg = z.link_hover, underline = true },
  ["@character"]              = { fg = z.string },
  ["@character.special"]      = { fg = z.string_escape },
  ["@number"]                 = { fg = z.number },
  ["@number.float"]           = { fg = z.number },
  ["@boolean"]                = { fg = z.boolean },
  ["@constant"]               = { fg = z.constant },
  ["@constant.builtin"]       = { fg = z.constant },
  ["@constant.macro"]         = { fg = z.preproc },
  ["@variable"]               = { fg = z.variable },
  ["@variable.builtin"]       = { fg = z.variable },
  ["@variable.parameter"]     = { fg = z.variable },
  ["@variable.member"]        = { fg = z.property },
  ["@property"]               = { fg = z.property },
  ["@field"]                  = { fg = z.property },
  ["@function"]               = { fg = z.func },
  ["@function.builtin"]       = { fg = z.func },
  ["@function.call"]          = { fg = z.func },
  ["@function.macro"]         = { fg = z.preproc },
  ["@function.method"]        = { fg = z.func },
  ["@function.method.call"]   = { fg = z.func },
  ["@constructor"]            = { fg = z.constructor, bold = true },
  ["@keyword"]                = { fg = z.keyword, bold = true },
  ["@keyword.function"]       = { fg = z.keyword, bold = true },
  ["@keyword.operator"]       = { fg = z.operator },
  ["@keyword.import"]         = { fg = z.keyword, bold = true },
  ["@keyword.type"]           = { fg = z.keyword, bold = true },
  ["@keyword.modifier"]       = { fg = z.keyword, bold = true },
  ["@keyword.repeat"]         = { fg = z.keyword, bold = true },
  ["@keyword.return"]         = { fg = z.keyword, bold = true },
  ["@keyword.conditional"]    = { fg = z.keyword, bold = true },
  ["@keyword.conditional.ternary"] = { fg = z.operator },
  ["@keyword.exception"]      = { fg = z.keyword, bold = true },
  ["@keyword.debug"]          = { fg = z.keyword, bold = true },
  ["@keyword.coroutine"]      = { fg = z.keyword, bold = true },
  ["@keyword.directive"]      = { fg = z.preproc },
  ["@keyword.directive.define"] = { fg = z.preproc },
  ["@operator"]               = { fg = z.operator },
  ["@type"]                   = { fg = z.type },
  ["@type.builtin"]           = { fg = z.type },
  ["@type.definition"]        = { fg = z.type },
  ["@type.qualifier"]         = { fg = z.keyword, bold = true },
  ["@attribute"]              = { fg = z.attribute },
  ["@attribute.builtin"]      = { fg = z.attribute },
  ["@label"]                  = { fg = z.label },
  ["@module"]                 = { fg = z.type },
  ["@module.builtin"]         = { fg = z.type },
  ["@tag"]                    = { fg = z.tag, bold = true },
  ["@tag.builtin"]            = { fg = z.tag, bold = true },
  ["@tag.attribute"]          = { fg = z.attribute },
  ["@tag.delimiter"]          = { fg = z.punctuation },
  ["@preproc"]                = { fg = z.preproc },
  ["@diff.plus"]              = { fg = z.created },
  ["@diff.minus"]             = { fg = z.deleted },
  ["@diff.delta"]             = { fg = z.modified },
  -- markup (Zed: title, text.literal, emphasis.strong)
  ["@markup.heading"]         = { fg = z.title, bold = true },
  ["@markup.strong"]          = { fg = z.constructor, bold = true },
  ["@markup.italic"]          = { italic = true },
  ["@markup.strikethrough"]   = { strikethrough = true },
  ["@markup.underline"]       = { underline = true },
  ["@markup.raw"]             = { fg = z.text_literal },
  ["@markup.raw.block"]       = { fg = z.text_literal },
  ["@markup.link"]            = { fg = z.link_hover },
  ["@markup.link.url"]        = { fg = z.link_hover, underline = true },
  ["@markup.link.label"]      = { fg = z.title },
  ["@markup.list"]            = { fg = z.punctuation },
  ["@markup.quote"]           = { fg = z.text_muted, italic = true },
  -- lsp semantic tokens
  ["@lsp.type.class"]         = { fg = z.type },
  ["@lsp.type.interface"]     = { fg = z.type },
  ["@lsp.type.enum"]          = { fg = z.type },
  ["@lsp.type.struct"]        = { fg = z.type },
  ["@lsp.type.type"]          = { fg = z.type },
  ["@lsp.type.typeParameter"] = { fg = z.type },
  ["@lsp.type.namespace"]     = { fg = z.type },
  ["@lsp.type.enumMember"]    = { fg = z.constant },
  ["@lsp.type.function"]      = { fg = z.func },
  ["@lsp.type.method"]        = { fg = z.func },
  ["@lsp.type.property"]      = { fg = z.property },
  ["@lsp.type.parameter"]     = { fg = z.variable },
  ["@lsp.type.variable"]      = { fg = z.variable },
  ["@lsp.type.number"]        = { fg = z.number },
  ["@lsp.type.string"]        = { fg = z.string },
  ["@lsp.type.operator"]      = { fg = z.operator },
  ["@lsp.type.keyword"]       = { fg = z.keyword, bold = true },
  ["@lsp.type.decorator"]     = { fg = z.attribute },
  ["@lsp.type.modifier"]      = { fg = z.keyword, bold = true },
  ["@lsp.type.comment"]       = {},
  ["@lsp.mod.readonly"]       = {},
  ["@lsp.mod.deprecated"]     = { strikethrough = true },
  -- diagnostics
  DiagnosticError            = { fg = z.error },
  DiagnosticWarn             = { fg = z.warning },
  DiagnosticInfo             = { fg = z.info },
  DiagnosticHint             = { fg = z.hint },
  DiagnosticOk               = { fg = z.created },
  DiagnosticUnderlineError   = { undercurl = true, sp = z.error },
  DiagnosticUnderlineWarn    = { undercurl = true, sp = z.warning },
  DiagnosticUnderlineInfo    = { undercurl = true, sp = z.info },
  DiagnosticUnderlineHint    = { undercurl = true, sp = z.hint },
  DiagnosticVirtualTextError = { fg = z.error, bg = z.error_bg },
  DiagnosticVirtualTextWarn  = { fg = z.warning, bg = z.warning_bg },
  DiagnosticVirtualTextInfo  = { fg = z.info, bg = z.info_bg },
  DiagnosticVirtualTextHint  = { fg = z.hint },
  DiagnosticUnnecessary      = { fg = z.ignored },
  DiagnosticDeprecated       = { strikethrough = true, sp = z.error },
  -- lsp
  LspReferenceText            = { bg = z.element_hover },
  LspReferenceRead            = { bg = z.element_hover },
  LspReferenceWrite           = { bg = z.element_hover },
  LspInlayHint                = { fg = z.hint, bg = z.element_hover },
  LspSignatureActiveParameter = { fg = z.cursor, bold = true },
  LspCodeLens                 = { fg = z.ignored },
  -- plugin groups mirroring Zed panels (surface.background for side panels)
  NormalSB                   = { fg = z.text, bg = z.surface },
  SignColumnSB               = { bg = z.surface },
  GitSignsAdd                = { fg = z.created },
  GitSignsChange             = { fg = z.modified },
  GitSignsDelete             = { fg = z.deleted },
  NeoTreeNormal              = { fg = z.text, bg = z.surface },
  NeoTreeNormalNC            = { fg = z.text, bg = z.surface },
  NeoTreeGitConflict         = { fg = z.conflict },
  NeoTreeGitIgnored          = { fg = z.ignored },
  NeoTreeGitUntracked        = { fg = z.hidden },
  SnacksPickerDir            = { fg = z.text_muted },
  TelescopeNormal            = { fg = z.text, bg = z.surface },
  TelescopeBorder            = { fg = z.border, bg = z.surface },
  TelescopeSelection         = { bg = z.element_sel },
  TelescopeMatching          = { fg = z.border_focused, bold = true },
  BlinkCmpMenu               = { fg = z.text, bg = z.surface },
  BlinkCmpMenuBorder         = { fg = z.border, bg = z.surface },
  BlinkCmpMenuSelection      = { bg = z.element_sel },
  BlinkCmpLabelMatch         = { fg = z.border_focused, bold = true },
  WhichKeyFloat              = { bg = z.surface },
}

for group, spec in pairs(hl) do
  vim.api.nvim_set_hl(0, group, spec)
end

for i, color in ipairs(z.ansi) do
  vim.g["terminal_color_" .. (i - 1)] = color
end
