#!/bin/bash

options=(
  # style=round
  width=10.0
  hidpi=on
  # TOKYO NIGHT
  # active_color=0xFF7AA2F7

  # SORA
  active_color=0xFF80C8E0

  # ROSE PINE
  # active_color=0xffc4a7e7
  # inactive_color=0xff6e6a86

  whitelist="ghostty,kitty"
)

borders "${options[@]}"
