#!/bin/bash

options=(
  # style=round
  width=3.0
  hidpi=on

  # CENDRE
  active_color=0xFFEA9875
  # SORA
  # active_color=0xFF80C8E0
  # KINTSUGI FLARED
  # active_color=0xFFE08542

  whitelist="ghostty,kitty"
)

borders "${options[@]}"
